In [ ]:
from pydantic import BaseModel, PositiveInt, ValidationError
from typing import Tuple, Literal

class Column(BaseModel):
    name: str = ""
    shape: Tuple[PositiveInt, PositiveInt] = (0, 0)
    data_type: Literal["int", "float", "str", "bool"]

external_data_01 = {
    "name": "id",
    "shape": (1,1),
    "data_type": "str"
}  

external_data_02 = {
    "name": "id",
    "shape": (0,0),
    "data_type": "list"
}  

try:
    Column(**external_data_01)  
    Column(**external_data_02)  
except ValidationError as e:
    print(e.errors())

## Real case

https://amazonwebshark.com/python-data-validation-and-observability-as-code-with-pydantic/

In [ ]:
!pip install fastexcel

In [3]:
import polars as pl 

file_path: str = "/home/user/py-pannguyen-learn/data/raw/sales_data_sample.xlsx"
df = pl.read_excel(file_path)
df.head()

shape: (5, 19)
┌───────────┬────────────┬────────────┬─────────┬───┬────────────┬───────────┬───────────┬─────────┐
│ Order_ID  ┆ Date       ┆ Category   ┆ Region  ┆ … ┆ Shipping_C ┆ Profit_Ma ┆ Profit    ┆ Month   │
│ ---       ┆ ---        ┆ ---        ┆ ---     ┆   ┆ ost        ┆ rgin      ┆ ---       ┆ ---     │
│ str       ┆ date       ┆ str        ┆ str     ┆   ┆ ---        ┆ ---       ┆ f64       ┆ str     │
│           ┆            ┆            ┆         ┆   ┆ f64        ┆ f64       ┆           ┆         │
╞═══════════╪════════════╪════════════╪═════════╪═══╪════════════╪═══════════╪═══════════╪═════════╡
│ ORD-10000 ┆ 2024-07-12 ┆ Books      ┆ East    ┆ … ┆ 0.0        ┆ 0.33      ┆ 83.57712  ┆ 2024-07 │
│ ORD-10001 ┆ 2025-03-15 ┆ Sports     ┆ West    ┆ … ┆ 0.0        ┆ 0.2       ┆ 251.784   ┆ 2025-03 │
│ ORD-10002 ┆ 2024-12-27 ┆ Home &     ┆ Central ┆ … ┆ 0.0        ┆ 0.37      ┆ 442.06749 ┆ 2024-12 │
│           ┆            ┆ Kitchen    ┆         ┆   ┆            ┆           ┆           ┆         │
│ ORD-10003 ┆ 2024-07-16 ┆ Home &     ┆ North   ┆ … ┆ 0.0        ┆ 0.23      ┆ 155.69815 ┆ 2024-07 │
│           ┆            ┆ Kitchen    ┆         ┆   ┆            ┆           ┆ 5         ┆         │
│ ORD-10004 ┆ 2024-06-11 ┆ Electronic ┆ North   ┆ … ┆ 0.0        ┆ 0.37      ┆ 1496.2356 ┆ 2024-06 │
│           ┆            ┆ s          ┆         ┆   ┆            ┆           ┆           ┆         │
└───────────┴────────────┴────────────┴─────────┴───┴────────────┴───────────┴───────────┴─────────┘

In [6]:
origin_cols: list = df.columns

In [13]:
def normailzed_columns(columns: pl.DataFrame.columns) -> list:
    return [col.strip().lower() for col in columns]
normalized_cols: list = normailzed_columns(origin_cols)
normalized_cols

['order_id',
 'date',
 'category',
 'region',
 'customer_segment',
 'payment_method',
 'quantity',
 'unit_price',
 'discount_rate',
 'customer_rating',
 'returned',
 'subcategory',
 'total_price',
 'discount_amount',
 'net_sales',
 'shipping_cost',
 'profit_margin',
 'profit',
 'month']

In [14]:
df.columns = normalized_cols
df.head()

shape: (5, 19)
┌───────────┬────────────┬────────────┬─────────┬───┬────────────┬───────────┬───────────┬─────────┐
│ order_id  ┆ date       ┆ category   ┆ region  ┆ … ┆ shipping_c ┆ profit_ma ┆ profit    ┆ month   │
│ ---       ┆ ---        ┆ ---        ┆ ---     ┆   ┆ ost        ┆ rgin      ┆ ---       ┆ ---     │
│ str       ┆ date       ┆ str        ┆ str     ┆   ┆ ---        ┆ ---       ┆ f64       ┆ str     │
│           ┆            ┆            ┆         ┆   ┆ f64        ┆ f64       ┆           ┆         │
╞═══════════╪════════════╪════════════╪═════════╪═══╪════════════╪═══════════╪═══════════╪═════════╡
│ ORD-10000 ┆ 2024-07-12 ┆ Books      ┆ East    ┆ … ┆ 0.0        ┆ 0.33      ┆ 83.57712  ┆ 2024-07 │
│ ORD-10001 ┆ 2025-03-15 ┆ Sports     ┆ West    ┆ … ┆ 0.0        ┆ 0.2       ┆ 251.784   ┆ 2025-03 │
│ ORD-10002 ┆ 2024-12-27 ┆ Home &     ┆ Central ┆ … ┆ 0.0        ┆ 0.37      ┆ 442.06749 ┆ 2024-12 │
│           ┆            ┆ Kitchen    ┆         ┆   ┆            ┆           ┆           ┆         │
│ ORD-10003 ┆ 2024-07-16 ┆ Home &     ┆ North   ┆ … ┆ 0.0        ┆ 0.23      ┆ 155.69815 ┆ 2024-07 │
│           ┆            ┆ Kitchen    ┆         ┆   ┆            ┆           ┆ 5         ┆         │
│ ORD-10004 ┆ 2024-06-11 ┆ Electronic ┆ North   ┆ … ┆ 0.0        ┆ 0.37      ┆ 1496.2356 ┆ 2024-06 │
│           ┆            ┆ s          ┆         ┆   ┆            ┆           ┆           ┆         │
└───────────┴────────────┴────────────┴─────────┴───┴────────────┴───────────┴───────────┴─────────┘

In [39]:
from pydantic import BaseModel, Field, ValidationError, field_validator
import datetime


class SaleDataModel(BaseModel):
    order_id: str = Field(
        min_length=1,
        max_length=50,
        validate_default=True,
        strict=True,
        repr=True
    )
    discount_rate: float = Field(
        ge=0,
        le=1,
        validate_default=True,
        strict=True,
        repr=True
    )
    month: str = Field(
        ge=datetime.date(2022, 1, 1).strftime("%Y-%m"),
        le=datetime.datetime.now().strftime("%Y-%m"),
        validate_default=True,
        strict=False,
        repr=True
    )

    @field_validator("order_id",  mode="before")
    @classmethod
    def validate_not_empty(cls, value, info):
        """Validate that a string field is not empty."""
        if str(value).strip() == "":
            raise ValueError(f"{info.field_name} must not be null, na or empty")
        return value

In [63]:
df_with_index = df.with_row_index()
index = 1
for row in df_with_index.iter_rows(named=True):
    try:
        validate_result = SaleDataModel(**row)
    except  (ValidationError, ValueError, Exception) as e:
        print(index, str(e))
    finally:
        index +=1

11 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
102 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
120 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
135 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
138 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
165 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
187 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
211 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
242 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
246 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
322 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
329 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
339 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
359 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
373 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
381 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
398 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
418 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
437 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
467 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
506 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
510 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
541 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
565 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
589 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
646 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
680 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
681 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
708 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
718 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
722 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
745 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
747 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
766 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
767 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
774 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
787 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
791 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
808 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
824 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
848 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
856 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
869 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
874 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
884 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
917 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
933 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
952 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
968 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
984 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type
993 1 validation error for SaleDataModel
discount_rate
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.12/v/float_type

In [ ]:
from enum import Enum

class HTTPMethod(Enum):
    POST = "POST"
    GET = "GET"

HTTPMethod.POST.value

In [ ]:
from enum import StrEnum

class Method(StrEnum):
    POST = "POST"

Method.POST.value